Migrate task planning
DukeRobotics/robosub-ros2 pull request #14
Opened 2024-10-26 16:25 UTC by JaredBaileyDuke

Removed python sonar files from this branch, and moved them to the migrate-sonar branch

2024-11-09 16:37 UTC, maxwellmlin commented
Task planning package ready for review. Still need to lint and test (see https://github.com/DukeRobotics/robosub-ros2/issues/3).

2025-02-07 05:22 UTC, viethungle-vt1401 requested changes
Search for and replace all instances of `%s` and `%d` string formatting with f-strings instead.

2025-02-07 05:22 UTC, viethungle-vt1401 commented on onboard/src/task_planning/task_planning/interface/cv.py
> +    FRAME_HEIGHT = 320
320 seems too low for `FRAME_HEIGHT`. Double check with Vedarsh and Max whether this should be 480 instead.

2025-02-07 05:22 UTC, viethungle-vt1401 commented on onboard/src/task_planning/task_planning/interface/cv.py
> +        bottom = 480
If `FRAME_HEIGHT` is 480, change this to `self.FRAME_HEIGHT`.

2025-02-07 05:22 UTC, viethungle-vt1401 commented on onboard/src/task_planning/task_planning/interface/cv.py
> +from geometry_msgs.msg import Point, Pose
```suggestion
from geometry_msgs.msg import Point, Pose
from rclpy.logging import get_logger
```

2025-02-07 05:22 UTC, viethungle-vt1401 commented on onboard/src/task_planning/task_planning/interface/cv.py
> +
```suggestion

logger = get_logger('cv')
```

2025-02-07 05:22 UTC, viethungle-vt1401 commented on onboard/src/task_planning/task_planning/interface/cv.py
> +            self.get_logger().warn(f'No bounding box data available for {gate_class}')
```suggestion
            logger.warning(f'No bounding box data available for {gate_class}')
```

2025-02-07 19:14 UTC, maxwellmlin commented on pyproject.toml
> +    "G004",
Specifically, ignore G004: https://docs.astral.sh/ruff/rules/logging-f-string/

2025-02-07 22:51 UTC, maxwellmlin commented on onboard/src/task_planning/task_planning/interface/controls.py
> +                raise ValueError(msg)
This is an intention linting rule. See https://docs.astral.sh/ruff/rules/f-string-in-exception/

2025-02-07 22:58 UTC, maxwellmlin commented on onboard/src/task_planning/task_planning/interface/controls.py
> +            set_control_types: Whether all axes should be set to DESIRED_TWIST
Nice catch. This was present in the original ROS 1 code as well.

2025-02-07 23:12 UTC, maxwellmlin commented on onboard/src/task_planning/task_planning/interface/cv.py
> +
I also added the `_interface` suffix to all interface loggers so we don't confuse them with the actual package.

2025-02-07 23:23 UTC, maxwellmlin commented on onboard/src/task_planning/task_planning/interface/cv.py
> +    FRAME_HEIGHT = 320
Traced to https://github.com/DukeRobotics/robosub-ros/commit/b9100fee3da52300b57de729847d577c6a395db0#diff-8c8914710202e28559cfbda7d13326854f71e5511d48855c3a8536e39c272641

2025-02-08 18:50 UTC, viethungle-vt1401 approved these changes
LGTM

2025-02-08 18:52 UTC, merged