Migrate CV
DukeRobotics/robosub-ros2 pull request #17
Opened 2024-11-04 00:37 UTC by nathanaelren

2025-01-16 22:33 UTC, maxwellmlin commented on docker/Dockerfile
> +RUN pip install depthai --break-system-packages
remove this

2025-01-23 20:32 UTC, viethungle-vt1401 commented on .gitignore
> +.db3
```suggestion

# Configuration files
.env
```

2025-01-24 00:05 UTC, viethungle-vt1401 requested changes

2025-01-24 00:05 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_camera_connect.py
> +"""
```suggestion
```

2025-01-24 00:05 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/image_tools.py
> +
```suggestion
```

2025-01-24 00:08 UTC, ChuChuCodes0414 commented on docker/Dockerfile
> +RUN apt-get update
This was added to fix an issue with `RUN apt install -y --no-install-recommends python3-opencv`, otherwise building via Github actions would result in the runner not finding this package.

2025-01-24 00:18 UTC, nathanaelren commented on docker/Dockerfile
> +RUN apt-get update
cuz otherwise build fails

2025-01-24 10:36 UTC, viethungle-vt1401 requested changes

2025-01-24 10:36 UTC, viethungle-vt1401 commented on .gitignore
> +.db3
```suggestion
# Configuration files
.env
```

2025-01-25 18:14 UTC, nathanaelren commented on onboard/src/cv/cv/buoy_detector_contour_matching.py
> +        upper_red_upper = np.array([179, 255, 255])
`config.py`

2025-01-25 19:25 UTC, viethungle-vt1401 requested changes

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_mono_detection.py
> +            # if object_msg.coords.x != 0 and object_msg.coords.y != 0 and object_msg.coords.z != 0:
Remove commented line.

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_mono_detection.py
> +        Define callback function for listenting to sonar response.
```suggestion
        Define callback function for listening to sonar response.
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_mono_detection.py
> +def main(args: list[str]|None=None) -> None:
```suggestion
def main(args: list[str] | None = None) -> None:
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +
```suggestion
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +        if num_saved_streams > MIN_NUM_SAVED_STREAMS:
```suggestion
        if num_saved_streams > 3:
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +        if num_saved_streams > MIN_NUM_SAVED_STREAMS:
Add noqa.

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +         # Set up publishers
```suggestion
        """Start publishers."""
        # Set up publishers
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +        """Build the DepthAI. Pipeline, which takes the RGB camera feed and retrieves it using an XLinkOut."""
```suggestion
        """Build the DepthAI pipeline, which takes the RGB camera feed and retrieves it using an XLinkOut."""
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +        """Build pipeline for left and right cams, ve left and rought, xout left and right."""
```suggestion
        """Build pipeline for left and right cams, ve left and right, xout left and right."""
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +        """Publish and saves."""
```suggestion
        """Publish and save."""
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_publish_save_streams.py
> +def main(args: None=None) -> None:
```suggestion
def main(args: None = None) -> None:
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +
```suggestion
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +            depth=10, # queue_size in ros 1
```suggestion
            depth=10,
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +    def build_pipeline(self, nn_blob_path: Path, sync_nn: bool) -> dai.Pipline:  # noqa: ARG002
```suggestion
    def build_pipeline(self, nn_blob_path: Path, sync_nn: bool) -> dai.Pipeline:  # noqa: ARG002
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +                # if sonar responds, then override existing robot-frame x info;
```suggestion
                # If sonar responds, then override existing robot-frame x info;
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +            # Flush out 0, 0, 0 values
```suggestion
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +        what sonar throws back if it is in range (> SONAR_RANGE = 1.75m)
```suggestion
        what sonar throws back if it is in range (> SONAR_RANGE = 1.75m).
```

2025-01-25 19:25 UTC, viethungle-vt1401 commented on onboard/src/cv/cv/depthai_spatial_detection.py
> +def main(args: list[str]|None=None) -> None:
```suggestion
def main(args: list[str] | None = None) -> None:
```

2025-01-25 22:10 UTC, viethungle-vt1401 requested changes
Please update and/or rewrite the README documentation for the cv package. It still contains descriptions for deprecated scripts and lacks descriptions for newer scripts (especially color correction and HSV detection scripts).

2025-01-30 23:48 UTC, ChuChuCodes0414 commented on onboard/src/cv/cv/path_marker_detector.py
> +
Auto formatting will insert this space, and removing it will cause linter issues.

2025-02-01 18:16 UTC, viethungle-vt1401 requested changes

2025-02-01 18:16 UTC, viethungle-vt1401 commented on onboard/src/cv/launch/camera_hard_reset.xml
The corresponding files `camera_hard_reset.py` and `camera_test_connect.py` have been deprecated.

2025-02-01 18:16 UTC, viethungle-vt1401 commented on onboard/src/cv/launch/depthai_camera_connect.xml
Make sure that the depthai launch files are compatible with ROS 2, and the arguments/params match their python scripts, then test these launch files.

2025-02-01 19:14 UTC, viethungle-vt1401 requested changes
Delete the `resource` folder in `cv` as we don't need it.

2025-02-01 19:14 UTC, viethungle-vt1401 commented on onboard/src/cv/README.md
>  The following are the folders and files in the CV package:
Please include descriptions for the other folders (`assets`, `config`, and `udev`).

2025-02-01 19:14 UTC, viethungle-vt1401 commented on onboard/src/cv/README.md
Move the `Structure` section to before the `DepthAI Camera` section (right after the intro paragraph).

2025-02-01 19:14 UTC, viethungle-vt1401 commented on onboard/src/cv/README.md
>  `camera_test_connect.launch` starts the `connect_depthai_camera` and `connect_usb_camera` services which determine whether the stereo and mono cameras are connected. There are no arguments to the lau
Both `camera_test_connect.py` and `ping_host.py` have been deprecated, so delete this section.

2025-02-04 23:02 UTC, viethungle-vt1401 requested changes
Review

2025-02-04 23:13 UTC, viethungle-vt1401 approved these changes

2025-02-05 01:25 UTC, closed without merging