Migrate foxglove
DukeRobotics/robosub-ros2 pull request #22
Opened 2024-11-24 19:38 UTC by maxwellmlin

- Bump ros-typescript-generator to 1.9.0
- Generate all ROS 2 interfaces at build time (instead of relying on commited file which may be outdated)
  - Note: this means `foxglove.py` must be run inside the container

2025-02-07 00:13 UTC, ChuChuCodes0414 approved these changes
LGTM
Very thoughtful comments & docs, excellent.

2025-02-07 00:24 UTC, nathanaelren commented
Hey @maxwellmlin, while reviewing your PR, I'd suggest the following code changes:

👉 [**Some small nitpicky tweaks to the readmes**](https://gitkraken.dev/drafts/7f5f5d40-2dc9-4d9a-814b-ed400224b67b?source=PRComment)
>

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/7f5f5d40-2dc9-4d9a-814b-ed400224b67b?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPTXVSSlhzNkM4cVdXIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

2025-02-07 00:27 UTC, nathanaelren requested changes
[**Some small nitpicky tweaks to the readmes**](https://gitkraken.dev/drafts/7f5f5d40-2dc9-4d9a-814b-ed400224b67b?source=PRComment)

2025-02-07 00:36 UTC, nathanaelren requested changes
Small readme updates

2025-02-07 00:36 UTC, nathanaelren commented on foxglove/README.md
> +> The `foxglove.py` CLI should be run *inside* the Docker container.
Explanation for how this can be done, e.g., `, even on your local machine. You can find instructions for this in the initial CS onboarding document.`

2025-02-07 00:36 UTC, nathanaelren commented on foxglove/README.md
> +```bash
Add `cd foxglove` before running the foxglove script

2025-02-07 00:36 UTC, nathanaelren commented on foxglove/README.md
> +```bash
Add `cd foxglove` before running the foxglove script

2025-02-07 00:36 UTC, nathanaelren commented on README.md
>  3. Open Foxglove Studio and connect to the WebSocket at `ws://IP_ADDRESS:28765`.
I can't add a comment on line 25, but maybe on line 25 add a bit more detail on Foxglove's capabilities and what we use it for, e.g.,:

We use [Foxglove Studio](https://foxglove.dev) for visualizing and debugging our code. Foxglove Studio is a web-based tool that allows us to visualize received data and send data in real time to ROS 2 topics and services in real-time.

2025-02-07 01:37 UTC, nathanaelren approved these changes
This is most excellent

2025-02-10 04:57 UTC, vedarshshah requested changes

2025-02-10 04:57 UTC, vedarshshah commented on lint.py
Linting JS and TS takes too long. While the other languages finish linting in 5 seconds, JS and TS take 2 minutes. Running ESLint on the entire repository takes 20 seconds, and running it on just the `foxglove` directory takes 7 seconds. I think we should refactor `lint.py` to run ESLint on the entire path passed to the CLI, instead of going file-by-file. It'll speed up local linting and cut down our GitHub Actions runtime.

2025-02-10 04:57 UTC, vedarshshah commented on lint.py
Please update the `lint.py` section in `SCRIPTS.md`.

2025-02-11 03:18 UTC, maxwellmlin commented on lint.py
- [ ] Revert changes to `lint.py`
- [ ] Add eslint scripts to root foxglove `package.json`
  - [ ] Lint
  - [ ] Lint & autofix
- [ ] Add `foxglove lint` subcommand that optionally takes a list of file paths to lint (by default, lints everything in foxglove)
  - [ ] Update foxglove CLI docs
- [ ] Add foxglove lint to actions workflow

2025-02-11 03:19 UTC, maxwellmlin commented on docker-compose.yml
> +      - ~/.foxglove-studio/:/root/.foxglove-studio
- [ ] Add note in SETUP.md (## Set Up the Docker Container)

2025-02-14 04:42 UTC, maxwellmlin commented on lint.py
Removed TS/JS from lint.py so docs no longer need update.

2025-02-14 04:44 UTC, maxwellmlin commented on .github/workflows/build-and-lint.yml
> +          docker compose exec robosub-ros2 bash /root/dev/robosub-ros2/.github/workflows/lint.sh
Moved foxglove linting from lint.py to foxglove.py. It is not a separate step in this workflow.

2025-02-14 04:51 UTC, maxwellmlin commented on docker/Dockerfile
> +
Tested

2025-02-15 17:23 UTC, vedarshshah commented on .github/workflows/build-and-lint.yml
> +        id: build-foxglove
```suggestion
        id: build-foxglove && steps.build-foxglove.outcome == 'success'
```

2025-02-15 17:26 UTC, vedarshshah commented on foxglove/README.md
> +> Building must be performed before local installing or publishing custom extensions. Additionally, building is a prerequisite for `lint.py` (eslint) and other Foxglove developer tools.
```suggestion
> Building must be performed before local installing or publishing custom extensions. Additionally, building is a prerequisite for `fox lint` (eslint) and other Foxglove developer tools.
```

2025-02-15 17:29 UTC, vedarshshah approved these changes
Address comments and merge

2025-02-15 18:16 UTC, merged